### ISSUE TITLE
Checkout gradle-syntatic-plugin

### ISSUE THREAD

**Issue by Scuilion** [simonhicks/gradle-vim-syntastic-plugin#4]
This plugin adds the features that you have here in your vim.gradle but it is included as a plugin (one line!) and runs automatically with the build task.

I like how you've added the .vimrc config to the local project. I'm definitely going to add that in the next release. 

https://github.com/Scuilion/gradle-syntastic-plugin

**Comment by simonhicks** [comment]
Yup. Yours is definitely better... I'll add a comment telling people to use your plugin instead of mine :)

Thanks!

**Comment by Scuilion** [comment]
If I'd of found your code first I would have copied it. ;) Hopefully I'll have checkstyle integrated in the plugin soon but I think I'm going to have to make some changes to syntastic.
